name: wget

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Wget
        run: wget -nc -c -k -K -r -l 1 --retry-on-http-error=429 --wait=10 --random-wait https://www.philosophizethis.org/transcripts

      - name: Save
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Saving...
          file_pattern: '*'
