name: wget

on:
  push:
    branches:
      - main
  
  schedule:
    - cron: '0 0 3 * *' # Repeat on day 3 of every month
 
  workflow_dispatch: # on button click

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        
      - name: Backup
        run: cp -r www.philosophizethis.org/ www.philosophizethis.org.BAK/

      - name: Wget
        run: wget -r -l 1 --retry-on-http-error=429 --wait=10 --random-wait https://www.philosophizethis.org/transcripts

      - name: Save
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Saving...
          file_pattern: '*'
